#!/bin/bash
#SBATCH --output=/home/junruz/prf_model/scripts/slurm_out/slurm-%j.out
#SBATCH -N 1
#SBATCH --job-name=prf_model
#SBATCH --time=10-00:00:00
#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --nodelist=mind-1-15
#SBATCH --mem=32G
#SBATCH --cpus-per-gpu=8


echo "SLURM_JOBID: " $SLURM_JOBID
source activate env2025
cd /home/junruz/prf_model/

python fit_prf_model_layerwise_nonzero.py \
--save_root /user_data/junruz/prf_models/no_zscore_drop \
--layer_name layer4

