#!/bin/bash
#SBATCH --output=/home/junruz/prf_model/scripts/slurm_out/slurm-%j.out
#SBATCH -N 1
#SBATCH --job-name=feat_ex
#SBATCH --time=10-00:00:00
#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --nodelist=mind-0-28
#SBATCH --mem=128G
#SBATCH --cpus-per-gpu=8


echo "SLURM_JOBID: " $SLURM_JOBID
source activate env2025
cd /home/junruz/prf_model/

python feature_extraction_CNN.py \
--batch_size 32 \
--model_name ADV_RN50 \
--layer_name layer4

