#!/bin/bash
#SBATCH --output=/home/junruz/prf_model/scripts/slurm_out/slurm-%A_%a.out
#SBATCH -N 1
#SBATCH --job-name=fit_prf
#SBATCH --time=10-00:00:00
#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --nodelist=mind-1-19
#SBATCH --mem=32G
#SBATCH --cpus-per-gpu=8
#SBATCH --array=0-4%5

echo "SLURM_JOBID: " $SLURM_JOBID
echo "SLURM_ARRAY_TASK_ID: " $SLURM_ARRAY_TASK_ID

echo "Running on node: " $SLURM_JOB_NODELIST
echo "GPU Information:"
nvidia-smi --query-gpu=name,memory.total --format=csv

source activate env2025
cd /home/junruz/prf_model/

MODELS=(DINO_RN50 ADV_RN50 OPEN_CLIP_RN50)
LAYERS=(relu layer1 layer2 layer3 layer4)
# MODELS=(OPEN_CLIP_CONVNEXT_BASE)
# LAYERS=(stem stage1 stage2 stage3 stage4)
# SPLIT_IDS=(1 2)

MODEL_INDEX=$((SLURM_ARRAY_TASK_ID % 1))
LAYER_ID=$((SLURM_ARRAY_TASK_ID / 1))
# SPLIT_INDEX=$((SLURM_ARRAY_TASK_ID / 5))

MODEL_NAME=${MODELS[$MODEL_INDEX]}
LAYER_NAME=${LAYERS[$LAYER_ID]}
# SPLIT_ID=${SPLIT_IDS[$SPLIT_INDEX]}

echo "Running model: " ${MODEL_NAME}
echo "Running layer: " ${LAYER_NAME}
echo "Running split: " ${SPLIT_ID}

python fit_prf_model_split_layerwise_zscore.py \
  --split_root /user_data/junruz/prf_models/fixed/split_1_zscore \
  --layer_name ${LAYER_NAME} \
  --model_name ${MODEL_NAME} \
  --split_id 1